title: OOP 26
description: Pemrograman Berorientasi Objek Gasal 2026 - S1 Kecerdasan Artifisial, Unesa
theme: just-the-docs

url: ""
baseurl: ""
permalink: pretty

search_enabled: true
heading_anchors: true
nav_enabled: true
nav_sort: case_sensitive

aux_links:
  "Course Info":
    - "/course-info/"
  "Staff":
    - "/staff/"
aux_links_new_tab: false

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Pemrograman Berorientasi Objek Gasal 2026 - S1 Kecerdasan Artifisial, Unesa"

color_scheme: light

sass:
  quiet_deps: true
  silence_deprecations: [import]