title: OOP '26
description: Pemrograman Berorientasi Objek Gasal 2026 - S1 Kecerdasan Artifisial, Universitas Negeri Surabaya
theme: just-the-docs

url: "https://oop-ai26.github.io"
baseurl: "/Praktikum-Gasal-2026"
permalink: pretty
color_scheme: wider

search_enabled: true
heading_anchors: true
nav_enabled: true
nav_sort: case_sensitive

aux_links:
  Dark Mode:
    - "#"
  "Course Info":
    - "https://oop-ai26.github.io/Praktikum-Gasal-2026/course-info/"
  "Staff":
    - "https://oop-ai26.github.io/Praktikum-Gasal-2026/staff/"
aux_links_new_tab: false

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Object-Oriented Programming '26 - TAs"

sass:
  quiet_deps: true
  silence_deprecations: [import]